DROP TABLE TBITENSPED;
DROP TABLE TBPEDIDO;
DROP TABLE TBPRODUTO;
DROP TABLE TBCLIENTE;

CREATE TABLE TBPRODUTO (
PKCODPROD NUMBER NOT NULL
, NOMEPROD VARCHAR2(20)
, ESTOQUEPROD integer
, ESTOQUEMIN integer
, VALORVENDAPROD NUMBER(10,2)
, QUATULTCOMPRA integer );

alter table TBPRODUTO add CONSTRAINT TBPRODUTO_PK PRIMARY KEY (PKCODPROD);

CREATE TABLE TBCLIENTE (
PKCODCLI NUMBER NOT NULL
, NOMECLI VARCHAR2(30)
, LIMITECOMPRA NUMBER(10,2)
, COMPRAREALIZADA NUMBER(10,2)
, SALDOLIBERADO NUMBER(10,2)
, ULTIMADATACOMPRA DATE);

alter table TBCLIENTE add CONSTRAINT TBCLIENTE_PK PRIMARY KEY (PKCODCLI);

CREATE TABLE TBPEDIDO (
PKCODPED NUMBER NOT NULL
, PKCODCLI NUMBER
, DATAPEDIDO DATE
, TOTALPEDIDO NUMBER(10,2)
);

alter table TBPEDIDO add CONSTRAINT TBPEDIDO_PK PRIMARY KEY (PKCODPED);
alter table TBPEDIDO add CONSTRAINT TBPEDIDO_FK FOREIGN KEY (PKCODCLI) REFERENCES
TBCLIENTE(PKCODCLI);

CREATE TABLE TBITENSPED (
PKCODITENS NUMBER NOT NULL
, FKCODPROD NUMBER
, FKCODPED NUMBER
, QUANTIDADE INTEGER
, VALORUNIT NUMBER(10,2)
, VALORTOTAL NUMBER(10,2)
);

alter table TBITENSPED add CONSTRAINT TBITENSPED_PK PRIMARY KEY (PKCODITENS);
alter table TBITENSPED add CONSTRAINT TBITENSPED_FK1 FOREIGN KEY (FKCODPROD) REFERENCES
TBPRODUTO(PKCODPROD);
alter table TBITENSPED add CONSTRAINT TBITENSPED_FK2 FOREIGN KEY (FKCODPED) REFERENCES
TBPEDIDO(PKCODPED);